### PR TITLE
refactor into new project directory structure (part 1)

### PR DESCRIPTION
**Pull request by tatianajiselle**
created the following as a part one refactor of the directory structure:

Screen Shot 2019-07-26 at 2 52 16 PM

### CODE REVIEW

**Comment by kcmartin** [comment]
I'm definitely on board with the new project structure, it will keep things cleaner and more organized.

**Comment by sepulworld** [comment]
Looks like tests need an update to work with new structure

**Comment by sepulworld** [comment]
Looks way better!

**Comment by tatianajiselle** [comment]
looks like the tests are passing now but the build broke? https://travis-ci.org/silvermullet/dinghy-ping/jobs/564817621 any suggestions?

**Comment by sepulworld** [comment]
> looks like the tests are passing now but the build broke? https://travis-ci.org/silvermullet/dinghy-ping/jobs/564817621 any suggestions?

Hmm, might be because this PR is a from a fork and the .travis.yml expects a $DOCKER_USERNAME which doesn't come through right.

```
Error parsing reference: "/dinghy-ping:build_472" is not a valid repository/tag: invalid reference format
```

Let's merge this in and we can validate things with `pr_false` image and then tag a release

**Comment by sepulworld** [comment]
Submitted an issue to fix the image build issue with forked repo PRs. https://github.com/silvermullet/dinghy-ping/issues/80

**Pull request merged**
