### PR TITLE
[Test ] Use flex 2column grid based ui for home page

### PR DESCRIPTION
**Pull request by balrubaye**
Hey guys what do u think about use two column and flex based to make it wrap for different screen sizes, Sorry I have not tested that locally just because I was getting errors so I will wait for CI to build then test it  :) 

Please let me know if you like that or not

### CODE REVIEW

**Comment by kcmartin** [comment]
Looks good!

Would it make sense to have the Right column elements left-aligned with each other?

**Comment by balrubaye** [comment]
> Looks good!
> 
> Would it make sense to have the Right column elements left-aligned with each other?

Thanks! After looking it at now I agree I could do that

**Comment by balrubaye** [comment]
this is how it looks now 
Screen Shot 2019-07-16 at 5 31 19 PM

**Comment by kcmartin** [comment]
Awesome, looks great!

**Comment by sepulworld** [comment]
Nice! The merge conflict should be easy to fix. I added one more box

**Comment by seeingidog2** [comment]
Nice! Can we resolve those and merge today? I have a few UI changes in mind and don't want to create more conflicts.

**Pull request merged**
